apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: osiz2k9gn-python
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe-python:1862a9a841b71c7eee3930053cce29532f939db6@sha256:169a444dadb2ffe614ebe77ddcb9e0574e3cbb4a411285b55c124f9621e5a2d9
          name: container-image
