apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: osiz2k9gn-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: osiz2k9gn-python 
  name: osiz2k9gn-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: osiz2k9gn-python 
